### ISSUE TITLE
Use preCreateChatMessage instead of createChatMessage hook

### ISSUE THREAD

**Issue by mkahvi** [spaceman02-ops/Inline-Table-Rolls#4]
Using preCreate~ eliminates the need for double update (create+update, I mean), which in turn makes the message handling snappier if there's lag anywhere along the line. It also removes the need for checking permissions for updating the message since it only cares about the creator (only creator gets the preCreate hook).

**Comment by spaceman02-ops** [comment]
If I recall correctly, I had to use the current process because table rolls are async but hooks don't allow for async functions within them. Then, I couldn't figure out how to store the message data from the hook without actually creating the message if that makes sense. I'll check this out though and circle back.

**Comment by mkahvi** [comment]
Ah, yes, that is indeed a reason for using post create hook. I don't think that has changed, so I'll close this as such.
